### ISSUE TITLE
SSH connections remain on target host

### ISSUE THREAD

**Issue by davidrabinowitz** [sunggun-yu/jenkins-capitomcat-plugin#28]
After deploying a war to a tomcat on a remote machine, there are many ssh connections left unclosed. For example, here is the result of ps after such session

``` bash
deploy   10933  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   10970  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   10988  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11001  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11012  0.0  0.1 135712  2292 ?        S    07:00   0:00 sshd: deploy@notty
deploy   11022  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11032  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11043  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11054  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11065  0.0  0.1 135520  2172 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11075  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11086  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11098  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11109  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11120  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11155  0.0  0.1 135520  2176 ?        S    07:00   0:00 sshd: deploy@pts/1
deploy   11168  0.0  0.1 135520  2172 ?        S    07:00   0:00 sshd: deploy@pts/1
```

The problem is that after several execution, the deploy fails:

``` bash
Starting Capitomcat Tomcat deploy
---------------------------------------------------------------------------
Capitomcat Tomcat Deploy : [Basic]
---------------------------------------------------------------------------
[10.7.40.43] Stopping Tomcat    : nohup /opt/tomcat8/bin/catalina.sh stop
ERROR: Exception while executing as deploy@10.7.40.43: Tomcat is not stopped.
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/capitomcat-1.2.1/lib/capitomcat/tasks/deploy.cap:115:in `check_tomcat_stopped'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/caps/capitomcat.cap:46:in `(root)'
org/jruby/RubyBasicObject.java:1738:in `instance_exec'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/sshkit-1.6.1/lib/sshkit/backends/netssh.rb:54:in `run'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/sshkit-1.6.1/lib/sshkit/runners/sequential.rb:21:in `run_backend'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/sshkit-1.6.1/lib/sshkit/runners/sequential.rb:16:in `execute'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/sshkit-1.6.1/lib/sshkit/coordinator.rb:17:in `each'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/capistrano-3.3.5/lib/capistrano/dsl.rb:55:in `on'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/caps/capitomcat.cap:20:in `(root)'
org/jruby/RubyProc.java:249:in `call'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
jar:file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/jruby-complete-1.7.3.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/capistrano-3.3.5/lib/capistrano/dsl.rb:16:in `invoke'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/capitomcat_action.rb:126:in `do_deploy'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/capitomcat_action.rb:33:in `execute'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/builder.rb:80:in `invoke'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/builder.rb:72:in `perform'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:14:in `perform'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:13:in `perform'

ERROR: Capitomcat deploy has failed (RuntimeError)
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/builder.rb:85:in `invoke'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/builder.rb:72:in `perform'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:14:in `perform'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
/var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:13:in `perform'

Build step 'Deploy WAR file to Tomcat via Capitomcat' marked build as failure
Finished: FAILURE
```

**Comment by luliangac** [comment]
I have the same question like you, and I think it's capitomcat's remote shell bug.

**Comment by wangjingfei** [comment]
I've got more than 4000+ unclosed sshd connections... Is there any way to close all of them in terminal?
