### ISSUE TITLE
Plugins is not visible on Jenkins 2.8

### ISSUE THREAD

**Issue by vndpundir** [sunggun-yu/jenkins-capitomcat-plugin#29]
I have installed this plugin on jenkins but it is not visible in Build Step.

**Comment by arnaudbichet** [comment]
It seems related to embedded jruby with jenkins 2.x on startup

Loading /var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/models/capitomcat/publisher.rb
load error: openssl -- java.lang.VerifyError: (class: org/jruby/ext/openssl/X509Cert, method: sign signature: (Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRuby
Object;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;) Incompatible argument to function (LoadError)
  org/jruby/RubyKernel.java:1027:in `require'
  jar:file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/jruby-complete-1.7.3.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:36:in`require'
  /var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/net-ssh-2.9.2/lib/net/ssh/transport/openssl.rb:2:in `(root)'
  org/jruby/RubyKernel.java:1027:in`require'
  jar:file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/jruby-complete-1.7.3.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:36:in `require'
  /var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/net-ssh-2.9.2/lib/net/ssh/buffer.rb:1:in`(root)'
  org/jruby/RubyKernel.java:1027:in `require'
  jar:file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/jruby-complete-1.7.3.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:36:in`require'
  /var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/net-ssh-2.9.2/lib/net/ssh/buffer.rb:2:in `(root)'
  org/jruby/RubyKernel.java:1027:in`require'
  jar:file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/jruby-complete-1.7.3.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:36:in `require'
  /var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:1:in`(root)'
  org/jruby/RubyKernel.java:1027:in `require'
  jar:file:/var/lib/jenkins/plugins/ruby-runtime/WEB-INF/lib/jruby-complete-1.7.3.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/custom_require.rb:36:in`require'
  /var/lib/jenkins/plugins/capitomcat/WEB-INF/classes/vendor/gems/gems/net-ssh-2.9.2/lib/net/ssh/transport/algorithms.rb:1:in `(root)'
  org/jruby/RubyKernel.java:1027:in`require'

**Comment by sagarsunkar** [comment]
Any workaround for this may be installing lower version of Ruby runtime will work?

Please advice

which version jenkins,capitomcat,ruby runtime will work ?

**Comment by mazkozi** [comment]
I have this problem in 2.19.4 version. Is this still an outstanding issue?

**Comment by markfaine** [comment]
I'm currently having this issue on 2.36.   Is there still no solution?

**Comment by markfaine** [comment]
@arnaudbichet  Where did you find the output you referenced above?  I'd like to see if I'm seeing the same.

**Comment by arnaudbichet** [comment]
I've just tested with 2.38 and similar issue with openssl. 
@markfaine You can find error into jenkins.log during jenkins startup.

**Comment by markfaine** [comment]
Thanks @arnaudbichet.   I tested it with 2.38 and it's also not working for me,  though I don't get the error message in the log file.

**Comment by blenard81** [comment]
Does anyone know how to get around the error:
load error: openssl -- java.lang.VerifyError: (class: org/jruby/ext/openssl/X509Cert, method: sign signature: (Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRuby
Object;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;) Incompatible argument to function (LoadError)
