### ISSUE TITLE
Fail to install ruby-runtime Windows 7 Jenkins 2.46.2 running as service JDK 8

### ISSUE THREAD

**Issue by yiukalun** [sunggun-yu/jenkins-capitomcat-plugin#32]
ruby-runtime	
Failure -

java.io.IOException: Inconsistent file length: expected 19016644 but only got 11227500
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1159)
Caused: hudson.util.IOException2: Failed to download from http://updates.jenkins-ci.org/download/plugins/ruby-runtime/0.12/ruby-runtime.hpi (redirected to: http://ftp-nyc.osuosl.org/pub/jenkins/plugins/ruby-runtime/0.12/ruby-runtime.hpi)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.download(UpdateCenter.java:1176)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1682)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1880)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1656)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Unknown Source)

**Comment by kashish1806** [comment]
I am also facing the same issue, anybody who knows the solution plz help
